google-ID: 'UA-113555461-1'

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'instagram', link: 'https://instagram.com/aldrinbalisi'}
- {icon: 'instagram', link: 'https://instagram.com/winnnf'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
